/**
 * Static location data pre-fetched from Back4App (10k members sampled).
 * Used to populate the location filter dropdowns immediately, before
 * dynamic data finishes loading. Regions include US states (full names,
 * abbreviations deduplicated) and international regions.
 */
export const STATIC_COUNTRIES = [
  'Algeria','Argentina','Australia','Austria','Belgium','Belize','Bolivia',
  'Bosnia and Herzegovina','Botswana','Brazil','Canada','Chile','Colombia',
  'Congo Republic','Costa Rica','Croatia','Curacao','Cyprus','Czechia','Denmark',
  'Ecuador','Egypt','El Salvador','Estonia','Eswatini','Ethiopia','Finland',
  'France','Germany','Ghana','Greece','Guam','Honduras','Hong Kong','Hungary',
  'Iceland','India','Iran','Iraq','Ireland','Israel','Italy','Jamaica','Japan',
  'Kazakhstan','Kenya','Latvia','Lithuania','Malawi','Malaysia','Maldives',
  'Mexico','Mongolia','Nepal','Netherlands','New Zealand','Nigeria','Pakistan',
  'Peru','Philippines','Poland','Portugal','Puerto Rico','Qatar','Romania',
  'Slovakia','Slovenia','South Africa','Spain','Suriname','Sweden','Switzerland',
  'Tanzania','Thailand','Trinidad and Tobago','Türkiye','Ukraine',
  'United Arab Emirates','United Kingdom','United States','Venezuela','Vietnam',
  'Zambia','Zimbabwe',
];

export const STATIC_REGIONS = [
  'Abia State','Addis Ababa','Aguadilla','Aguascalientes','Alabama',
  'Alajuela Province','Alaska','Alberta','Amhara','Andalusia','Ankara','Antalya',
  'Antioquia','Anzoátegui','Apure','Aragon','Aragua','Arizona','Arkansas',
  'Ashanti Region','Atlántico','Attica','Auckland','Australian Capital Territory',
  'Baden-Wurttemberg','Baghdad','Bagmati Province','Bahia','Baja California',
  'Baja California Sur','Baladīyat ad Dawḩah','Balearic Islands','Barinas',
  'Basilicate','Basque Country','Bavaria','Bay of Plenty','Belize District','Bern',
  'Bihor County','Bogota D.C.','Bolívar','Bratislava Region','Brazzaville',
  'British Columbia','Brittany','Brussels Capital','București','Budapest',
  'Buenos Aires','Buenos Aires F.D.','Calabarzon','Caldas Department','California',
  'Campeche','Canary Islands','Canterbury','Capital Region','Carabobo',
  'Castille and León','Castille-La Mancha','Catalonia','Cauca Department',
  'Central District','Central Greece','Central Region','Cesar Department',
  'Chaguanas','Chiapas','Chihuahua','Chubut','City of Zagreb','Coahuila',
  'Cojedes','Colorado','Connacht','Connecticut','Cordillera','Cordoba',
  'Corrientes','Couva-Tabaquite-Talparo','Cundinamarca','Dar es Salaam Region',
  'Davao Region','Dededo','Delaware','Departamento de Bolívar',
  'Departamento de Boyacá','Departamento del Cauca','Departamento del Chocó',
  'District of Columbia','Distrito Federal','Durango','East','Eastern Cape',
  'Emilia-Romagna','England','Entre Rios','Estado Trujillo','Falcón',
  'Federation of Bosnia and Herzegovina','Flanders','Florida','Formosa',
  'Francisco Morazán Department','Free State','Gaborone','Galicia','Gauteng',
  'Georgia','Gharbia','Giza','Goiás','Guanajuato','Guerrero','Guárico',
  'Hamburg','Harare','Harjumaa','Hawaii',"Hawke's Bay Region",'Hesse','Hidalgo',
  'Ho Chi Minh','Idaho','Illinois','Indiana','Iowa','Islamabad','Istanbul',
  'Jalisco','Jujuy','Kaafu Atoll','Kansas','Karnataka','Kentucky','Kerala',
  'Kingston','Koshi','Krabi','KwaZulu-Natal','Kwai Tsing District','La Rioja',
  'Lagos','Lara','Lazio','Leinster','Liberecký kraj','Lima region',
  'Limassol District','Limpopo','Lisbon','Ljubljana','Lombardy','Louisiana',
  'Lower Saxony','Lower Silesia','Lusaka Province','Lvivska Oblast','Madrid',
  'Maharashtra','Maine','Manawatu-Wanganui','Manitoba','Manzini Region',
  'Maryland','Massachusetts','Melilla','Mendoza','Metro Manila','Mexico City',
  'Michigan','Michoacán','Minnesota','Miranda','Misiones','Mississippi','Missouri',
  'Monagas','Montana','Morelos','Mpumalanga','Munster','Murcia','Mérida','México',
  'Nagaland','Nairobi County','Nariño','National Capital Territory of Delhi',
  'Navarre','Nayarit','Nebraska','Neuquen','Nevada','New Brunswick',
  'New Hampshire','New Jersey','New Mexico','New South Wales','New York',
  'Newfoundland and Labrador','Nitra Region','Norte de Santander Department',
  'North Carolina','North Dakota','North Holland','North Rhine-Westphalia',
  'North West','Northern Cape','Northern Ireland','Northern Territory','Northland',
  'Northwest Territories','Nova Scotia','Nueva Esparta','Nuevo León','Nunavut',
  'Oaxaca','Ohio','Oklahoma','Ontario','Oregon','Otago','Overijssel',
  'Paramaribo District','Pavlodar Region','Pennsylvania','Phuket','Pichincha',
  'Port of Spain','Portuguesa','Prague','Primorje-Gorski Kotar County',
  'Prince Edward Island','Principality of Asturias','Provincia de San José',
  'Puebla','Punjab','Quebec','Queensland','Querétaro','Quintana Roo','Rajasthan',
  'Razavi Khorasan','Rheinland-Pfalz','Rhode Island','Rio Negro','Rivers State',
  'Roraima','Rīga','Salta','San Juan','San Luis','San Luis Potosí',
  'San Salvador Department','Santa Cruz','Santa Cruz Department','Santa Fe',
  'Santander Department','Santiago Metropolitan','Santiago del Estero',
  'Saskatchewan','Saxony','Scotland','Selangor','Silesia','Sinaloa','Sindh',
  'Skikda','Sonora','South Australia','South Carolina','South Dakota',
  'South Holland','South Ostrobothnia','Southern Region','Southwest Finland',
  'State of Berlin','Stockholm County','Sucre','São Paulo','Tabasco','Tamaulipas',
  'Tamil Nadu','Tasman District','Tasmania','Tehran','Tel Aviv','Telangana',
  'Tennessee','Texas','Tlaxcala','Tokyo','Tolima Department','Tucuman','Táchira',
  'Ulaanbaatar','Ulster','Utah','Uttarakhand','Uusimaa','Valencia',
  'Valle del Cauca Department','Vargas','Veracruz','Vermont','Victoria','Vienna',
  'Vilnius','Virginia','Vukovar-Srijem County','Värmland County',
  'Västra Götaland County','Waikato Region','Wales','Washington',
  'Wellington Region','West Virginia','Western Australia','Western Cape',
  'Wisconsin','Wyoming','Yaracuy','Yucatán','Yukon','Zacatecas','Zulia','Zurich',
  'Île-de-France',
];

export const STATIC_CITIES = [
  'Acme','Albany','Albuquerque','Allen Park','Anaheim','Andover','Arlington',
  'Athens','Atlanta','Auckland','Bagillt','Bakersfield','Bangkok','Baton Rouge',
  'Bel Air','Boca Raton','Boston','Bremerton','Brentwood','Brighton','Brooklyn',
  'Browns Mills','Buford','Burlington','Burwell','Calgary','Camden',
  'Castilleja de Guzmán','Castle Rock','Chambersburg','Charlotte','Cheltenham',
  'Chesterland','Chicago','Christchurch','Clute','Columbus','Commack','Concord',
  'Conroe','Coquitlam','Corinth','Cornwall','Coventry','Cypress','Dacula',
  'Dallas','Dar es Salaam','Denver','Des Plaines','Dilley','Dobson','Douglas',
  'Doylestown','Drums','Dulles','Durham','Easley','East Hartford','East Windsor',
  'Edmonton','El Cajon','El Paso','El Sobrante','Elmsford','Ennis','Esparto',
  'Eugene','Fairbanks','Fairfax','Falls Church','Fargo','Flint','Forden','Forest',
  'Fort Worth','Fresno','Galena','Gastonia','Georgetown','Glasgow','Glastonbury',
  'Gloucester City','Golden','Grand Rapids','Grants Pass','Greenwood Village',
  'Hanover','Harlan','Harrisonburg','Harrisville','Hartford','Hartland','Hemet',
  'Highland','Hilliard','Houston','Hudson','Indianapolis','Kansas City','Lagos',
  'Lanark','Lancaster','Lansing','Las Vegas','Lawrenceville','Lebanon','Leeds',
  'Littleton','Liverpool','Londonderry','Los Altos','Los Angeles','Louisville',
  'Lubbock','Lynnwood','Macedon','Manassas','Manchester','Market Harborough',
  'Martinsburg','Melbourne','Memphis','Miami','Middletown','Milton','Milwaukee',
  'Minneapolis','Missoula','Mobile','Montreal','Morristown','Murfreesboro',
  'New York','Newburgh','Newcastle upon Tyne','Newport Beach','Newton Aycliffe',
  'Norfolk','North Las Vegas','North Royalton','Oakland','Oklahoma City',
  'Orland Park','Orlando','Overland Park','Oxford','Oxnard','Palm Coast',
  'Palmerton','Panama City','Pasco','Philadelphia','Phoenix','Pinckney',
  'Pittsburgh','Plattsburgh','Portland','Portsmouth','Pueblo','Queens','Quincy',
  'Raleigh','Regina','Rhododendron','Richmond','Riverside','Roanoke','Royse City',
  'Salem','Salisbury','San Antonio','San Bernardino','San Francisco','Santa Rosa',
  'Santee','Seattle','Sharjah','Sheffield','Simpsonville','Singapore','Somerville',
  'Southampton','Southwark','Spring Valley','Springfield','St Louis','Stafford',
  'Sunderland','Swansea','Sydney','Tampa','Tavares','Tempe','Tempe Junction',
  'The Bronx','Thornton','Toronto','Tucson','Vancouver','Vero Beach',
  'Virginia Beach','Washington','Waterbury','West Chester','Willimantic',
  'Wilmington','Winnipeg','Woodland Hills','Worcester','Youngstown',
];
